name: Deploy Blazor Static site to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
 
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v3.2.0
              with:
                  dotnet-version: 8.x
                  include-prerelease: true 

            - name: dotnet workload restore
              run: dotnet workload restore
            
            - name: Publish .NET Core Project
              run: dotnet publish StaticBlog3.csproj -c Release -o release --nologo

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  GITHUB_TOKEN: $'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'
                  BRANCH: gh-pages
                  FOLDER: release/wwwroot
